/*
    https://projecteuler.net/problem=12
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

    1: 1
    3: 1,3
    6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?

    Just getAmountOfDivisors then checkIfOver continue if not
*/

var amount = 500;
console.log(getOverDivisors(amount));


function getOverDivisors(count){
    var currTrig = 1;
    var amountToUp = 2;
    while(getAmountOfDivisors(currTrig) < count){
        currTrig += amountToUp;
        amountToUp++;
    }
    return currTrig;
}

function getAmountOfDivisors(num){
    amount = 2;
    if(num % 2 == 0){
        amount += 2;
    }
    for(var i = 3; i <= Math.sqrt(num); i++){
        if(num % i == 0){
            if(num / i == i){
                amount++;
            } else {
                amount += 2;
            }
        }
    }
    return amount;
}