'''
    https://projecteuler.net/problem=29

    Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

    22=4, 23=8, 24=16, 25=32
    32=9, 33=27, 34=81, 35=243
    42=16, 43=64, 44=256, 45=1024
    52=25, 53=125, 54=625, 55=3125
    If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

    4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

    How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
'''
import time
import math
def getAllPowers(aHighest,bHighest):
    arr = []
    for i in range(2,aHighest+1):
        for k in range(2,bHighest+1):
            arr.append(pow(i,k))
    arr.sort()
    newArr = []
    for i in range(0,len(arr) - 1):
        if(arr[i] != arr[i+1]):
            newArr.append(arr[i])

    return newArr
def main():
    startTime = time.time()
    print(getAllPowers(5,5))
    endTime = time.time()
    print(endTime - startTime, " Seconds taken")

if(__name__ == "__main__"):
    main()