/*
    https://projecteuler.net/problem=2
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

    This could be way more efficent however this problem was done quickly so I do not see the need for it now
    Just getting fibonacci numbers and checking with modulus if they are even or odd then suming
*/



/* var term1 = 0;
var term2 = 1;

for(var i = 0; i < 8; i++){
    newTerm = term1 + term2;
    console.log(newTerm);
    oldTerm1 = term1;
    term1 = term2;
    term2 = oldTerm1 + term2;
} */

var total = 0;
var num1 = 0;
var num2 = 1;
var limit = 4000000;
while(true){
    if(num1 + num2 > limit){
        break;
    }
    if((num1 + num2) % 2 == 0){
        total += num1 + num2;
    }
    oldNum1 = num1;
    num1 = num2;
    num2 = oldNum1 + num2;
}
console.log(total);